services:
  - type: worker
    name: ict-sniper-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python ict_bot.py
    envVars:
      - key: TG_TOKEN
        sync: false
