services:
  - type: web
    name: ict-sniper-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: TG_TOKEN
        sync: false
