services:
  - type: worker
    name: ict-sniper-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python ict_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
